# Dependencies
markdown:            kramdown
highlighter:         rouge

# Gems (for Jekyll 3.0)
plugins: [jekyll-paginate, jekyll-feed]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Gros
tagline:             ''
description:         ''
url:                 https://grosquildu.github.io
baseurl:             
paginate:            7

# About/contact
author:
  name:              Gros
  url:               --
  email:             e2.8a.95@gmail.com

# Custom vars
version:             ⊕ǷǷ⊕

# Social Media
github:				http://github.com/GrosQuildu

exclude:      ["assets/pwnablekr/plain/*"]

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:    
           https://github.com/ariestiyansyah/naringu

collections:
  pwnablekr:
    output: true
    permalink: /pwnablekr/:path/